name: Coingecko API - Publish python

on:
  push:
    branches:
      - master

jobs:
  publish-pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -r dev_requirements.txt -r requirements.txt
        working-directory: ./client/python

      - name: Build sdist
        run: python setup.py sdist
        working-directory: ./client/python

      - name: Publish package
        run: |
          python -m twine upload --repository-url ${{ secrets.PYPI_OFFICIAL_UPLOAD_URL }} -u __token__ -p ${{ secrets.PYPI_TOKEN }} --skip-existing dist/*
        working-directory: ./client/python
